openapi: 3.0.3
info:
  title: Casa do Código Service
  description: Casa do Código HTTP service
  version: "1.0"
servers:
- url: http://localhost:3333/actors
  description: hosts for Casa do Código Service.
paths:
  /actors:
    post:
      tags:
      - actors
      summary: create_actor actors
      operationId: actors#create_actor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActorRequestBody'
            example:
              description: 5qz
              e-mail: andreanne_reichert@hayes.org
              name: Sunt ducimus.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorDTO'
              example:
                created_at: Ut incidunt molestiae voluptates.
                description: 88u
                e-mail: trent_jacobs@schimmel.org
                id: Aut vel hic deleniti accusamus debitis dolor.
                name: Et aperiam laboriosam sed et.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
  /categories:
    post:
      tags:
      - categories
      summary: create_category categories
      operationId: categories#create_category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequestBody'
            example:
              name: Ab delectus quam aut.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
              example:
                id: Possimus velit.
                name: Commodi sed ratione tempore est.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    ActorDTO:
      type: object
      properties:
        created_at:
          type: string
          example: Voluptate et omnis sapiente.
        description:
          type: string
          example: 6q8
          maxLength: 400
        e-mail:
          type: string
          example: rudolph@volkman.com
          format: email
        id:
          type: string
          example: Ut autem molestiae et omnis ut ipsa.
        name:
          type: string
          example: Rem et quae harum laborum dolore aperiam.
      example:
        created_at: Et necessitatibus impedit quam.
        description: wdh
        e-mail: lucinda_lueilwitz@gulgowskijerde.com
        id: Ad iure numquam.
        name: Aut in sint magni dignissimos est.
      required:
      - id
      - name
      - e-mail
      - description
      - created_at
    CategoryDTO:
      type: object
      properties:
        id:
          type: string
          example: Ducimus voluptatum.
        name:
          type: string
          example: Dignissimos et occaecati dolorem.
      example:
        id: Eum sit est.
        name: Dolorum in autem.
      required:
      - id
      - name
    CreateActorRequestBody:
      type: object
      properties:
        description:
          type: string
          example: qet
          maxLength: 400
        e-mail:
          type: string
          example: cooper_little@romaguera.name
          format: email
        name:
          type: string
          example: Harum eos dolores.
      example:
        description: ly7
        e-mail: rocio_mann@stroman.biz
        name: Cupiditate illo non voluptas.
      required:
      - name
      - e-mail
      - description
    CreateCategoryRequestBody:
      type: object
      properties:
        name:
          type: string
          example: Hic quibusdam sint et quos atque assumenda.
      example:
        name: Quia et dolore unde incidunt ipsum rerum.
      required:
      - name
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        fault: true
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: false
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
