swagger: "2.0"
info:
  title: Service for Casa do Código
  description: HTTP service for Casa do Código
  version: ""
host: localhost:3333
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /actors:
    post:
      tags:
      - actors
      summary: create actors
      operationId: actors#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ActorsCreateRequestBody'
          required:
          - name
          - e-mail
          - description
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/ActorsCreateResponseBody'
            required:
            - id
            - name
            - e-mail
            - description
            - created_at
      schemes:
      - http
  /swagger.json:
    get:
      tags:
      - actors
      summary: Download ../../gen/http/openapi.json
      operationId: actors#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  ActorsCreateRequestBody:
    title: ActorsCreateRequestBody
    type: object
    properties:
      description:
        type: string
        example: ox9
        maxLength: 400
      e-mail:
        type: string
        example: Et ut recusandae.
      name:
        type: string
        example: Quisquam hic qui labore nihil iure.
    example:
      description: 3i3
      e-mail: Explicabo eum dolores.
      name: Delectus nulla qui.
    required:
    - name
    - e-mail
    - description
  ActorsCreateResponseBody:
    title: ActorsCreateResponseBody
    type: object
    properties:
      created_at:
        type: string
        example: Id in animi omnis at est.
      description:
        type: string
        example: oo0
        maxLength: 400
      e-mail:
        type: string
        example: Earum odit quas.
      id:
        type: string
        example: Nihil libero dolorum laboriosam.
      name:
        type: string
        example: Et voluptatem et ab.
    example:
      created_at: Odio velit.
      description: yyt
      e-mail: Suscipit mollitia.
      id: Assumenda fugit.
      name: Quia aliquid aut enim voluptas.
    required:
    - id
    - name
    - e-mail
    - description
    - created_at
