openapi: 3.0.3
info:
  title: Casa do Código Service
  description: Casa do Código HTTP service
  version: "1.0"
servers:
- url: http://localhost:3333
  description: hosts for Casa do Código Service.
paths:
  /actors:
    post:
      tags:
      - actors
      summary: create_actor actors
      operationId: actors#create_actor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActorRequestBody'
            example:
              description: 0av
              e-mail: pietro_reinger@corkery.info
              name: Et qui beatae ut quia aliquid eligendi.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorDTO'
              example:
                created_at: Commodi sed neque libero.
                description: 1i7
                e-mail: queenie.jaskolski@bogisichklein.info
                id: In qui quo non.
                name: Aut exercitationem.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /books:
    get:
      tags:
      - books
      summary: list_books books
      operationId: books#list_books
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTO'
                example:
                - actor_id: Nihil eligendi omnis voluptatem.
                  category_id: Et eum.
                  id: Quia a voluptatem adipisci placeat rem.
                  isbn: Nihil qui aut perferendis provident alias facilis.
                  issue: Perferendis cum accusamus ea omnis.
                  pages: 5576691719649980440
                  price: 20.947353
                  summary: Assumenda minima debitis provident odio.
                  synopsis: u6t
                  title: Sit accusamus provident cupiditate hic.
                - actor_id: Nihil eligendi omnis voluptatem.
                  category_id: Et eum.
                  id: Quia a voluptatem adipisci placeat rem.
                  isbn: Nihil qui aut perferendis provident alias facilis.
                  issue: Perferendis cum accusamus ea omnis.
                  pages: 5576691719649980440
                  price: 20.947353
                  summary: Assumenda minima debitis provident odio.
                  synopsis: u6t
                  title: Sit accusamus provident cupiditate hic.
                - actor_id: Nihil eligendi omnis voluptatem.
                  category_id: Et eum.
                  id: Quia a voluptatem adipisci placeat rem.
                  isbn: Nihil qui aut perferendis provident alias facilis.
                  issue: Perferendis cum accusamus ea omnis.
                  pages: 5576691719649980440
                  price: 20.947353
                  summary: Assumenda minima debitis provident odio.
                  synopsis: u6t
                  title: Sit accusamus provident cupiditate hic.
                - actor_id: Nihil eligendi omnis voluptatem.
                  category_id: Et eum.
                  id: Quia a voluptatem adipisci placeat rem.
                  isbn: Nihil qui aut perferendis provident alias facilis.
                  issue: Perferendis cum accusamus ea omnis.
                  pages: 5576691719649980440
                  price: 20.947353
                  summary: Assumenda minima debitis provident odio.
                  synopsis: u6t
                  title: Sit accusamus provident cupiditate hic.
              example:
              - actor_id: Nihil eligendi omnis voluptatem.
                category_id: Et eum.
                id: Quia a voluptatem adipisci placeat rem.
                isbn: Nihil qui aut perferendis provident alias facilis.
                issue: Perferendis cum accusamus ea omnis.
                pages: 5576691719649980440
                price: 20.947353
                summary: Assumenda minima debitis provident odio.
                synopsis: u6t
                title: Sit accusamus provident cupiditate hic.
              - actor_id: Nihil eligendi omnis voluptatem.
                category_id: Et eum.
                id: Quia a voluptatem adipisci placeat rem.
                isbn: Nihil qui aut perferendis provident alias facilis.
                issue: Perferendis cum accusamus ea omnis.
                pages: 5576691719649980440
                price: 20.947353
                summary: Assumenda minima debitis provident odio.
                synopsis: u6t
                title: Sit accusamus provident cupiditate hic.
              - actor_id: Nihil eligendi omnis voluptatem.
                category_id: Et eum.
                id: Quia a voluptatem adipisci placeat rem.
                isbn: Nihil qui aut perferendis provident alias facilis.
                issue: Perferendis cum accusamus ea omnis.
                pages: 5576691719649980440
                price: 20.947353
                summary: Assumenda minima debitis provident odio.
                synopsis: u6t
                title: Sit accusamus provident cupiditate hic.
              - actor_id: Nihil eligendi omnis voluptatem.
                category_id: Et eum.
                id: Quia a voluptatem adipisci placeat rem.
                isbn: Nihil qui aut perferendis provident alias facilis.
                issue: Perferendis cum accusamus ea omnis.
                pages: 5576691719649980440
                price: 20.947353
                summary: Assumenda minima debitis provident odio.
                synopsis: u6t
                title: Sit accusamus provident cupiditate hic.
    post:
      tags:
      - books
      summary: create_book books
      operationId: books#create_book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequestBody'
            example:
              actor_id: Soluta eos ipsa ad.
              category_id: Quisquam in cum numquam.
              isbn: Minus est ipsa.
              issue: Earum qui est nam quos aperiam quidem.
              pages: 8283409113468120753
              price: 20.110447
              summary: Eos et culpa perspiciatis voluptatem doloremque eum.
              synopsis: j73
              title: Non enim.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
              example:
                actor_id: Eos aliquam vitae numquam culpa similique.
                category_id: Fuga quas.
                id: Exercitationem atque velit.
                isbn: Totam provident ratione ea.
                issue: Totam qui id.
                pages: 6683934939303022064
                price: 20.160345
                summary: Quaerat consequuntur.
                synopsis: 60t
                title: Eius ut ut.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /categories:
    post:
      tags:
      - categories
      summary: create_category categories
      operationId: categories#create_category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequestBody'
            example:
              name: Fuga ex.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
              example:
                id: Temporibus est.
                name: Quia reiciendis aut sed soluta.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    ActorDTO:
      type: object
      properties:
        created_at:
          type: string
          example: Quidem earum esse enim.
        description:
          type: string
          example: 9vp
          maxLength: 400
        e-mail:
          type: string
          example: roman@spencervon.org
          format: email
        id:
          type: string
          example: Amet consequatur.
        name:
          type: string
          example: Eos ut repellat est praesentium nostrum excepturi.
      example:
        created_at: Deleniti nobis.
        description: 89n
        e-mail: elyssa.renner@green.name
        id: Facere quis fugit.
        name: Aliquid beatae sequi in placeat.
      required:
      - id
      - name
      - e-mail
      - description
      - created_at
    BookDTO:
      type: object
      properties:
        actor_id:
          type: string
          example: Quae neque eum et natus omnis.
        category_id:
          type: string
          example: Hic beatae exercitationem itaque necessitatibus.
        id:
          type: string
          example: Deserunt expedita ratione.
        isbn:
          type: string
          example: Expedita minus quia nobis reprehenderit.
        issue:
          type: string
          example: Quos aut aliquid.
        pages:
          type: integer
          example: 3301727903157585340
          minimum: 100
        price:
          type: number
          example: 20.60122
          minimum: 20
        summary:
          type: string
          example: Occaecati eligendi fugit mollitia.
        synopsis:
          type: string
          example: oe8
          maxLength: 500
        title:
          type: string
          example: Culpa omnis nihil.
      example:
        actor_id: Quae dolorum.
        category_id: Natus eaque recusandae alias itaque ipsa.
        id: Sint id.
        isbn: Dolor sit asperiores et inventore asperiores doloribus.
        issue: Saepe ad.
        pages: 2958065447482187856
        price: 20.866953
        summary: Est recusandae sed harum voluptates quia.
        synopsis: zvd
        title: Sed sit.
      required:
      - id
      - title
      - synopsis
      - price
      - pages
      - isbn
      - issue
      - category_id
      - actor_id
    CategoryDTO:
      type: object
      properties:
        id:
          type: string
          example: Animi sed eos iure.
        name:
          type: string
          example: Quaerat corporis harum praesentium consequatur dolor quam.
      example:
        id: Sint dignissimos.
        name: Dolores qui doloremque provident id ut tenetur.
      required:
      - id
      - name
    CreateActorRequestBody:
      type: object
      properties:
        description:
          type: string
          example: 8da
          maxLength: 400
        e-mail:
          type: string
          example: vickie@ornwest.name
          format: email
        name:
          type: string
          example: Eum consequatur rem sunt voluptates sed amet.
      example:
        description: n1p
        e-mail: vivien@bartonbatz.net
        name: Non voluptatem.
      required:
      - name
      - e-mail
      - description
    CreateBookRequestBody:
      type: object
      properties:
        actor_id:
          type: string
          example: Ut culpa recusandae et rem distinctio.
        category_id:
          type: string
          example: Facilis asperiores.
        isbn:
          type: string
          example: Ut soluta.
        issue:
          type: string
          example: Consequatur eveniet expedita dolore quod ratione.
        pages:
          type: integer
          example: 4441684894377169495
          minimum: 100
        price:
          type: number
          example: 20.599264
          minimum: 20
        summary:
          type: string
          example: Velit necessitatibus recusandae non.
        synopsis:
          type: string
          example: 55g
          maxLength: 500
        title:
          type: string
          example: Qui molestias.
      example:
        actor_id: Ut qui et eius dolore.
        category_id: Deserunt error ea tempore minus omnis aspernatur.
        isbn: Nisi molestiae aliquid nesciunt et.
        issue: Mollitia rerum ullam.
        pages: 4787081792796410834
        price: 20.744522
        summary: Quas aut quis culpa dolor.
        synopsis: hii
        title: Dolore enim quia.
      required:
      - title
      - synopsis
      - price
      - pages
      - isbn
      - issue
      - category_id
      - actor_id
    CreateCategoryRequestBody:
      type: object
      properties:
        name:
          type: string
          example: Ex ex voluptas.
      example:
        name: Omnis facere veniam porro.
      required:
      - name
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        fault: true
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
