openapi: 3.0.3
info:
  title: Casa do Código Service
  description: Casa do Código HTTP service
  version: "1.0"
servers:
- url: http://localhost:3333/actors
  description: hosts for Casa do Código Service.
paths:
  /actors:
    post:
      tags:
      - actors
      summary: create_actor actors
      operationId: actors#create_actor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActorRequestBody'
            example:
              description: h7r
              e-mail: Dicta rerum nesciunt perspiciatis.
              name: Sint atque.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorDTO'
              example:
                created_at: Aperiam reprehenderit labore voluptas adipisci fugit.
                description: lif
                e-mail: Accusamus aut hic aut officiis totam.
                id: Quia aut voluptatem.
                name: Odit at illo enim voluptatibus.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /categories:
    post:
      tags:
      - categories
      summary: create_category categories
      operationId: categories#create_category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequestBody'
            example:
              name: Aperiam veritatis excepturi quia ab est.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
              example:
                id: Rerum id illo ea ea sit.
                name: Qui alias ad repudiandae amet.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    ActorDTO:
      type: object
      properties:
        created_at:
          type: string
          example: Sequi exercitationem aut laborum minus fugit iste.
        description:
          type: string
          example: yhm
          maxLength: 400
        e-mail:
          type: string
          example: Et doloremque.
        id:
          type: string
          example: Necessitatibus molestiae quam a amet voluptas.
        name:
          type: string
          example: Vero voluptas iure praesentium veritatis suscipit.
      example:
        created_at: Neque libero dolorem.
        description: 7qo
        e-mail: Sit sint dolores.
        id: Eius molestiae dicta alias.
        name: Molestiae asperiores.
      required:
      - id
      - name
      - e-mail
      - description
      - created_at
    CategoryDTO:
      type: object
      properties:
        id:
          type: string
          example: Perspiciatis voluptatem doloremque eum eos.
        name:
          type: string
          example: Sit minus est.
      example:
        id: Aut earum qui.
        name: Nam quos aperiam quidem necessitatibus.
      required:
      - id
      - name
    CreateActorRequestBody:
      type: object
      properties:
        description:
          type: string
          example: q0a
          maxLength: 400
        e-mail:
          type: string
          example: Similique ut.
        name:
          type: string
          example: Commodi sed ratione tempore est.
      example:
        description: 60i
        e-mail: Quo non nam aut exercitationem aut.
        name: Autem in.
      required:
      - name
      - e-mail
      - description
    CreateCategoryRequestBody:
      type: object
      properties:
        name:
          type: string
          example: Enim dolor qui.
      example:
        name: Vitae debitis eos et.
      required:
      - name
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: false
        timeout: true
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
