swagger: "2.0"
info:
  title: Casa do Código Service
  description: Casa do Código HTTP service
  version: ""
host: localhost:3333
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /actors:
    post:
      tags:
      - actors
      summary: create_actor actors
      operationId: actors#create_actor
      parameters:
      - name: create_actor_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/ActorsCreateActorRequestBody'
          required:
          - name
          - e-mail
          - description
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ActorsCreateActorResponseBody'
            required:
            - id
            - name
            - e-mail
            - description
            - created_at
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ActorsCreateActorInvalidFieldsResponseBody'
      schemes:
      - http
  /categories:
    post:
      tags:
      - categories
      summary: create_category categories
      operationId: categories#create_category
      parameters:
      - name: create_category_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CategoriesCreateCategoryRequestBody'
          required:
          - name
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CategoriesCreateCategoryResponseBody'
            required:
            - id
            - name
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CategoriesCreateCategoryInvalidFieldsResponseBody'
      schemes:
      - http
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  ActorsCreateActorInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_actor_invalid_fields_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ActorsCreateActorRequestBody:
    title: ActorsCreateActorRequestBody
    type: object
    properties:
      description:
        type: string
        example: iiv
        maxLength: 400
      e-mail:
        type: string
        example: Ea quas soluta unde dolores similique.
      name:
        type: string
        example: Et dolorem accusantium accusantium.
    example:
      description: yyv
      e-mail: Assumenda et qui beatae ut quia.
      name: Eum quaerat quas cumque natus voluptatem.
    required:
    - name
    - e-mail
    - description
  ActorsCreateActorResponseBody:
    title: ActorsCreateActorResponseBody
    type: object
    properties:
      created_at:
        type: string
        example: Veritatis delectus voluptas qui quibusdam ducimus.
      description:
        type: string
        example: w4v
        maxLength: 400
      e-mail:
        type: string
        example: Harum dolorem.
      id:
        type: string
        example: Debitis cumque atque consequuntur aliquid.
      name:
        type: string
        example: Atque necessitatibus praesentium facere sed non ea.
    example:
      created_at: Accusamus debitis dolor nulla.
      description: qpw
      e-mail: Consequuntur ex eum aut nesciunt aperiam.
      id: Suscipit mollitia exercitationem dicta ut error voluptatem.
      name: Aliquam id illum.
    required:
    - id
    - name
    - e-mail
    - description
    - created_at
  CategoriesCreateCategoryInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_category_invalid_fields_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CategoriesCreateCategoryRequestBody:
    title: CategoriesCreateCategoryRequestBody
    type: object
    properties:
      name:
        type: string
        example: Ab delectus quam aut.
    example:
      name: Possimus velit.
    required:
    - name
  CategoriesCreateCategoryResponseBody:
    title: CategoriesCreateCategoryResponseBody
    type: object
    properties:
      id:
        type: string
        example: At quam cum.
      name:
        type: string
        example: Optio eum iusto delectus quae.
    example:
      id: Dolores maxime ut.
      name: Molestiae voluptates.
    required:
    - id
    - name
